### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Tac-O-Lanthan** [Tac-O-Lanthan/furima-33053#10]
お世話になります。
フリマアプリを下記フォーマットの通り提出します。

***
### Heroku URL
- https://furima-33053on90.herokuapp.com/

### basic認証
- ID：on90
- Pass：on90

### 出品者
- email：foobar@foobar
- pass：foobar2828

### 購入者
- email：hogehoge@hogehoge
- pass：hogehoge2828

### カード情報
- number：4242424242424242
- exp-month：3
- exp-year：33
- cvc：123
***

ご確認よろしくお願い申し上げます。

**Comment by mo1015** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]

- [x] **ログイン状態の出品者に、「編集・削除ボタン」が表示され、商品情報編集ページに遷移できるようにしましょう**
- [x] **ログイン状態の出品者以外のユーザーのみ、「購入画面に進むボタン」が表示されるようにしましょう**

上記により編集・削除と購入ができないため、関連する機能については修正後に確認させていただきます。

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Tac-O-Lanthan** [comment]
お世話になります。

***
## 修正点
- 正しい順番でユーザーと商品の状態を検証できるよう、showビューのif条件分の入れ子部分を入れ替えました。
- 正しく商品の売却状態を検証できるように記述を変更しました。
***

よろしくお願い申し上げます。

**Comment by naru6117** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/49669977/106257269-a7b4ef00-625f-11eb-89e4-26dee228b13f.png)


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
